config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  devise_scope :user do
    root to: "devise/sessions#new"
  end

  namespace :admin do
    get 'transactions/index'
    resources :dashboard, only: [:index, :new, :create, :edit, :update, :show] do
      get 'pending_sign_ups', to: 'dashboard#pending_sign_ups', on: :collection
      get 'all_users', to: 'dashboard#all_users', on: :collection
     
    end
  end
  
  namespace :trader do
    get 'portfolios/index'
    resources :dashboard, only: [:index, :show, :edit, :update] do
      get 'top_up', to: 'dashboard#top_up', on: :collection
      post 'top_up', to: 'dashboard#top_up', on: :collection
    end

    resources :transactions, only: [:index, :new, :create]
    resources :portfolios, only: [:index]

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
    before_action :set_user, only: %i[show edit update]

    def index
        @users = User.where(role: :trader)
        @pending_traders = User.where(role: :trader, status: 'pending')
        @stock_prices = fetch_stock_prices(['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'TSLA'])
        @market_news = fetch_market_news
    end

    def pending_sign_ups
        @pending_traders = User.where(role: :trader, status: 'pending')
    end

    def all_users
        @admins = User.where(role: :admin)
        @approved_traders = User.where(role: :trader, status: 'approved')
    end
    

    def new
        @user = User.new(role: :trader)
    end
  
    def create
        @user = User.new(trader_params)
        if @user.save
            if @user.status == 'approved'
                UserMailer.approved_email(@user).deliver_later
            end
            redirect_to admin_dashboard_index_path, notice: 'Trader was created successfully.'
        else
            render :new, status: :unprocessable_entity
        end
    end
      

    def edit
    end

    def update
        if @user.update(trader_params.except(:id, :password, :password_confirmation))
          if @user.saved_change_to_status?
            if @user.status == 'approved'
              UserMailer.approved_email(@user).deliver_later
            end
          end
          redirect_to admin_dashboard_path(@user), notice: 'Trader info updated successfully.'
        else
          render :edit
        end
    end

    def show
    end

 
      

    private

    def set_user
        @user = User.find(params[:id])
    end

    def trader_params
        params.require(:user).permit(:status, :first_name, :last_name, :email, :password, :password_confirmation, :role)
    end

    def fetch_stock_prices(symbols)
        begin
          client = IEX::Api::Client.new
          stock_prices = symbols.map { |symbol| client.quote(symbol) }
          stock_prices
        rescue IEX::Errors::ClientError => e
          flash[:alert] = "Error fetching stock prices: #{e.message}"
          Rails.logger.error("Error fetching stock prices: #{e.message}")
          []
        end
      end

      def fetch_market_news
        begin
          client = IEX::Api::Client.new
          symbols = ['TSLA', 'GOOGL', 'AMZN']
          news = []
      
          symbols.each do |symbol|
            symbol_news = client.news(symbol).take(1)
            news.concat(symbol_news)
          end
      
          Rails.logger.debug("Market News: #{news.inspect}")
          news || [] 
        rescue IEX::Errors::ClientError => e
          flash[:alert] = "Error fetching market news: #{e.message}"
          Rails.logger.error("Error fetching market news: #{e.message}")
          []
        end
      end
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
end

app/controllers/trader/dashboard_controller.rb
class Trader::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    if params[:search].present?
      begin
        @stock = IEX::Api::Client.new.quote(params[:search])
      rescue IEX::Errors::SymbolNotFoundError
        @stock = nil
      end
        
        @market_news = fetch_market_news
        Rails.logger.debug("Market News: #{@market_news.inspect}")
    end

    begin
      @stocks = IEX::Api::Client.new.stock_market_list(:mostactive)
    rescue IEX::Errors::SymbolNotFoundError
      @stocks = []
    end

    @transactions = current_user.transactions
  end

  def top_up
    @top_up_amount = 0.0

    if request.post?
      top_up_amount = params[:top_up_amount].to_f

      if top_up_amount > 0
        current_user.top_up_balance(top_up_amount)
        flash[:notice] = "Successfully topped up your balance."
        redirect_to trader_dashboard_index_path
        return
      else
        flash.now[:alert] = "Top-up amount is invalid."
        render :top_up
      end
    end

    
  end
end


private

def set_user
  @user = User.find(params[:id])
end

def fetch_market_news
  begin
    client = IEX::Api::Client.new
    symbols = ['NFLX', 'BABA', 'FB']
    news = []

    symbols.each do |symbol|
      symbol_news = client.news(symbol).take(1)
      news.concat(symbol_news)
      Rails.logger.debug("Market News for #{symbol}: #{symbol_news.inspect}")
    end

    Rails.logger.debug("Market News: #{news.inspect}")
    news || [] 
  rescue IEX::Errors::ClientError => e
    flash[:alert] = "Error fetching market news: #{e.message}"
    Rails.logger.error("Error fetching market news: #{e.message}")
    []
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/trader/dashboard_helper.rb
module Trader::DashboardHelper
end

app/views/admin/dashboard/_edit_status_form.html.erb
<div class="wrapper">
<!-- Sidebar -->
<div class="sidebar">
  <div class="logo-container">
  <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
  <span class="website-name">Stock Harbor</span>
  </div>
  <!-- <h1>Hello, <%= current_user.first_name %>!</h1> -->
  <div class="menu-items">
    <%= link_to 'Add New User', new_admin_dashboard_path %>
    <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
    <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
    <%= link_to 'See All Transactions', admin_transactions_index_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
  </div>
</div>

<%= form_for trader, url: admin_dashboard_path(trader), method: :patch, html: { class: 'edit-status-form' } do |f| %>
  <div class='field'>
    <%= f.label :status, class: 'status-label' %>
    <div class="status-radio-buttons">
      <%= f.radio_button :status, :pending, class: 'pending-radio' %>
      <%= f.label :pending, class: 'radio-label' %> 
    </div>
    <div class="status-radio-buttons">
      <%= f.radio_button :status, :approved, class: 'approved-radio' %>
      <%= f.label :approved, class: 'radio-label' %> 
    </div>
  </div>

  <div class='actions'>
    <%= f.submit class: 'submit-button' %>
  </div>



<% end %>

app/views/admin/dashboard/_form.html.erb
<div class="wrapper">
<!-- Sidebar -->
<div class="sidebar">
<div class="logo-container">
<%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
<span class="website-name">Stock Harbor</span>
</div>
  <div class="menu-items">
    <%= link_to 'Add New User', new_admin_dashboard_path %>
    <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
    <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
    <%= link_to 'See All Transactions', admin_transactions_index_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
  </div>
</div>

<%= form_for user, url: user.persisted? ? admin_dashboard_path(user) : admin_dashboard_index_path, method: user.persisted? ? :patch : :post do |f| %>
  
  <div class="error-container">
    <% if f.object.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(f.object.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% f.object.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  
  <div class='field mb-3'>
    <%= f.label :first_name, class: 'form-label text-light' %>
    <%= f.text_field :first_name, class: 'form-control bg-light text-dark', placeholder: 'Enter first name' %>
  </div>

  <div class='field mb-3'>
    <%= f.label :last_name, class: 'form-label text-light' %>
    <%= f.text_field :last_name, class: 'form-control bg-light text-dark', placeholder: 'Enter last name' %>
  </div>

  <div class='field mb-3'>
    <%= f.label :email, class: 'form-label text-light' %>
    <%= f.email_field :email, class: 'form-control bg-light text-dark', placeholder: 'Enter email address' %>
  </div>

  <div class='field mb-3'>
    <%= f.label :password, class: 'form-label text-light' %>
    <%= f.password_field :password, class: 'form-control bg-light text-dark', placeholder: 'Enter password' %>
  </div>

  <div class='field mb-3'>
    <%= f.label :password_confirmation, class: 'form-label text-light' %>
    <%= f.password_field :password_confirmation, class: 'form-control bg-light text-dark', placeholder: 'Confirm password' %>
  </div>

  <div class='field mb-3'>
    <%= f.label :status, class: 'form-label text-light d-block' %>
    <!--
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, :pending, class: 'form-check-input', id: 'pending_radio' %>
      <%= f.label :pending, class: 'form-check-label text-light', for: 'pending_radio' %>
    </div>-->
    <div class="form-check form-check-inline">
      <%= f.radio_button :status, :approved, checked: true, class: 'form-check-input', id: 'approved_radio' %>
      <%= f.label :approved, class: 'form-check-label text-light', for: 'approved_radio' %>
    </div>
  </div>

  <div class='field mb-3'>
    <%= f.label :role, class: 'form-label text-light d-block' %>
    <div class="form-check form-check-inline">
      <%= f.radio_button :role, :trader, checked: true, class: 'form-check-input', id: 'trader_radio' %>
      <%= f.label :trader, class: 'form-check-label text-light', for: 'trader_radio' %>
    </div>
    <!--
    <div class="form-check form-check-inline">
      <%= f.radio_button :role, :admin, class: 'form-check-input', id: 'admin_radio' %>
      <%= f.label :admin, class: 'form-check-label text-light', for: 'admin_radio' %>
    </div>-->
    
  </div>

  <div class='actions'>
    <%= f.submit 'Create User', class: 'btn btn-success' %>
    <%= link_to 'Back to Home', admin_dashboard_index_path, class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/admin/dashboard/all_users.html.erb
<div class="wrapper">
<div class="sidebar">
<div class="logo-container">
<%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
<span class="website-name">Stock Harbor</span>
</div>
<div class="menu-items">
<%= link_to 'Add New User', new_admin_dashboard_path %>
<%= link_to 'See All Users', '/admin/dashboard/all_users' %>
<%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
<%= link_to 'See All Transactions', admin_transactions_index_path %>
<%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
</div>
</div>

<!-- Content -->
<div class="content-wrapper">
  <div class="see-all-traders">
    <div class="trader-list">
      <h2 class="list-heading">List of all Approved Traders</h2>
      <table class="user-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Registration Date</th>
          </tr>
        </thead>
        <tbody>
          <% @approved_traders.sort_by(&:created_at).reverse.each do |user| %>
            <tr>
              <td><%= link_to "#{user.first_name.capitalize} #{user.last_name.capitalize}", admin_dashboard_path(user), class: 'custom-link' %></td>
              <td><%= user.email %></td>
              <td><%= user.role.capitalize %></td>
              <td><%= user.status.capitalize %></td>
              <td><%= user.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Back to Home', admin_dashboard_index_path, class: 'btn btn-primary' %>

    </div>
  </div>
</div>
</div>

app/views/admin/dashboard/edit.html.erb
<div class="wrapper">
<!-- Sidebar -->
<div class="sidebar">
  <div class="logo-container">
    <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
  </div>
  <!-- <h1>Hello, <%= current_user.first_name %>!</h1> -->
  <div class="menu-items">
    <%= link_to 'Add New User', new_admin_dashboard_path %>
    <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
    <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
    <%= link_to 'See All Transactions', admin_transactions_index_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
  </div>
</div>

<div class="new-wrapper">
<div class="new-user">
  <h1 style="color: #fc4d2d;">Edit Trader Info</h1>
  <%= render 'form', user: @user %>
  </div>
</div>
</div>

app/views/admin/dashboard/index.html.erb
<div class="wrapper">
<div class="sidebar">
  <div class="logo-container">
    <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
    <span class="website-name">Stock Harbor</span>
  </div>
    <div class="menu-items">
      <%= link_to 'Add New User', new_admin_dashboard_path %>
      <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
      <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
      <%= link_to 'See All Transactions', admin_transactions_index_path %>

      <hr class="menu-divider">
      <%= link_to 'Account Summary', '#', class: 'custom-link dividends' %>
      <%= link_to 'Stock Alerts', '#', class: 'custom-link stock-alerts' %>
      <%= link_to 'Market Analysis', '#', class: 'custom-link market-analysis' %>
      <%= link_to 'Risk Management', '#', class: 'custom-link risk-management' %>
      <%= link_to 'Tax Information', '#', class: 'custom-link tax-information' %>
     
      
      <hr class="menu-divider">
      <%= link_to 'Mobile App', '#', class: 'custom-link mobile-app' %>
      <%= link_to 'Watchlist', '#', class: 'custom-link watchlist' %>
      <%= link_to 'Research', '#', class: 'custom-link research' %>
      <%= link_to 'Dividends', '#', class: 'custom-link dividends' %>
      <%= link_to 'Settings', '#', class: 'custom-link settings' %>
      <%= link_to 'Reports', '#', class: 'custom-link reports' %>
      <%= link_to 'Educational Resources', '#', class: 'custom-link educational-resources' %>
      <%= link_to 'Support', '#', class: 'custom-link support' %>
      <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>

    
    </div>
 
  </div>

  <!-- Main Content -->
<div class="admin-content">
  <div class="admin-wrapper">
  <h1 class="wrapper-header">Welcome, <span style="color: #21ce99;"><%= current_user.first_name %></span>!</h1>

    
    <div class="table-box">
      <h1 class="stock-heading">Current Stock Prices</h1>
      <table class="stock-table">
        <thead>
          <tr>
            <th>Symbol</th>
            <th>Company Name</th>
            <th>Latest Price</th>
            <th>Change Percent</th>
            <th>Volume</th>
          </tr>
        </thead>
        <tbody>
          <% @stock_prices.each do |stock_price| %>
            <tr>
              <td><%= stock_price.symbol %></td>
              <td><%= stock_price.company_name %></td>
              <td>$<%= stock_price.latest_price %></td>
              <td><%= stock_price.change_percent %></td>
              <td><%= stock_price.iex_volume %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>


    <div class="flex-container">
    <div class="news-box">
    <h1 class="news-heading">Market News</h1>
    <% @market_news.each do |article| %>
      <div class="news-article">
        <h3 class="article-title"><%= article['headline'] %></h3>
        <p class="article-source">Source: <%= article['source'] %></p>
      </div>
    <% end %>
  </div>
  
  <div class="graph-box">
  <h1 class="box-heading">Stock Prices Graph</h1>
  <div id="stockGraph"></div>
</div>

</div>
</div>
</div>

  

  

app/views/admin/dashboard/new.html.erb
<div class="wrapper">
<!-- Sidebar -->
<div class="sidebar">
<div class="logo-container">
<%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
<span class="website-name">Stock Harbor</span>
</div>
  <div class="menu-items">
    <%= link_to 'Add New User', new_admin_dashboard_path %>
    <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
    <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
    <%= link_to 'See All Transactions', admin_transactions_index_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
  </div>
</div>


<div class="new-wrapper">
<div class="new-user">
  <h1 style="color: #fc4d2d;">Create New Trader</h1>
  <%= render 'form', user: @user %>
 
</div>

</div>

</div>

app/views/admin/dashboard/pending.html.erb
=======
<div class='admin-dash-wrapper'>

<div class='add-new-trader'>
    <%= link_to 'Add New Trader', new_admin_dashboard_path %>
</div>

<div class='pending-traders'>
    <h1>Pending Trader Applications</h1>
    <% @pending_traders.each do |trader| %>
        <div class='trader-card'>
            <h3>
                <%= "#{trader.first_name} #{trader.last_name}" %>
            </h3>
            <p>Email: <%= trader.email %></p>
            <p>Registration Date: <%= trader.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></p>
              <%= render 'edit_status_form', trader: trader %>
        </div>
    <% end %>
</div>

<div class='approved-traders'>
  <h1>List of all Approved Traders</h1>
  <% User.where(role: :trader, status: :approved).each do |trader| %>
    <div class='trader-card approved'>
      <h3>
         <%= link_to "#{trader.first_name} #{trader.last_name}", admin_dashboard_path(trader) %>
      </h3>
      <p>Email: <%= trader.email %></p>
      <p>Role: <%= trader.role %></p>
      <p>Status: <%= trader.status %></p>
      <p>Registration Date:<%= trader.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></p>
    </div>
  <% end %>
</div>

</div>

app/views/admin/dashboard/pending_sign_ups.html.erb
<div class="wrapper">
<!-- Sidebar -->
<div class="sidebar">
  <div class="logo-container">
  <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
  <span class="website-name">Stock Harbor</span>
  </div>
  <!-- <h1>Hello, <%= current_user.first_name %>!</h1> -->
  <div class="menu-items">
    <%= link_to 'Add New User', new_admin_dashboard_path %>
    <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
    <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
    <%= link_to 'See All Transactions', admin_transactions_index_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
  </div>
</div>



<div class='admin-dash-wrapper'>
  <div class='pending-traders'>
    <h2 class='pending-header'>Pending Trader Applications</h2>
    <table class='trader-table'>
      <thead>
        <tr class='table-header'>
          <th class='column'>Name</th>
          <th class='column'>Email</th>
          <th class='column'>Registration Date</th>
          <th class='column'>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @pending_traders.each do |trader| %>
          <tr class='trader-row'>
            <td class='column'><%= "#{trader.first_name} #{trader.last_name}" %></td>
            <td class='column'><%= trader.email %></td>
            <td class='column'><%= trader.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></td>
            <td class='column'>
              <%= render 'edit_status_form', trader: trader %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Back to Home', admin_dashboard_index_path, class: 'btn btn-primary mt-4' %>
  </div>
</div>

app/views/admin/dashboard/show.html.erb
<div class="wrapper">
<!-- Sidebar -->
<div class="sidebar">
<div class="logo-container">
  <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
  <span class="website-name">Stock Harbor</span>
  </div>
  <!-- <h1>Hello, <%= current_user.first_name %>!</h1> -->
  <div class="menu-items">
    <%= link_to 'Add New User', new_admin_dashboard_path %>
    <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
    <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
    <%= link_to 'See All Transactions', admin_transactions_index_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>
  </div>
</div>

<div class='show-container'>
  <div class='show-card'>
    <div class='card-header'>
      <h1 class='card-title'>User Details</h1>
    </div>
    <div class='show-card-body'>
      <h2 class='user-name'><%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}" %></h2><hr>
      <p class='card-text'>User ID: <%= @user.id %></p>
      <p class='card-text'>Email: <%= @user.email %></p>
      <p class='card-text'>Role: <%= @user.role.capitalize %></p>
      <p class='card-text'>Status: <%= @user.status.capitalize %></p>
      <p class='card-text'>Registration Date: <%= @user.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></p>
      <div class='card-footer'>
      <%= link_to 'Edit User Info', edit_admin_dashboard_path(@user), class: 'btn btn-success' %> ||  <%= link_to 'Back to Home', admin_dashboard_index_path, class: 'btn btn-primary' %>
    </div>
    </div>
    
  </div>
</div>