config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  devise_scope :user do
    root to: "devise/sessions#new"
  end

  namespace :admin do
    get 'transactions/index'
    resources :dashboard, only: [:index, :new, :create, :edit, :update, :show] do
      get 'pending_sign_ups', to: 'dashboard#pending_sign_ups', on: :collection
      get 'all_users', to: 'dashboard#all_users', on: :collection
     
    end
  end
  
  namespace :trader do
    get 'portfolios/index'
    resources :dashboard, only: [:index, :show, :edit, :update] do
      get 'top_up', to: 'dashboard#top_up', on: :collection
      post 'top_up', to: 'dashboard#top_up', on: :collection
    end

    resources :transactions, only: [:index, :new, :create]
    resources :portfolios, only: [:index]

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all

    if params[:search_email].present?
      @transactions = @transactions.joins(:user).where('users.email LIKE ?', "%#{params[:search_email]}%")
    end
    
  end
end

app/controllers/trader/transactions_controller.rb
class Trader::TransactionsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @user = current_user
      @transactions = @user.transactions
    end
  
    def new
      @transaction = current_user.transactions.new(transaction_params)
    end
  
    def create
      @transaction = current_user.transactions.new(transaction_params)
      if @transaction.save
          redirect_to trader_transactions_path, notice: "Transaction successful."
          update_user_balance
      else
        flash.now[:alert] = "Transaction cannot proceed."
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def transaction_params
      params.require(:transaction).permit(:stock_symbol, :quantity, :price, :transaction_type, :user_id)
    end
  
    def update_user_balance
      if @transaction.buy?
        current_user.update(balance: current_user.balance - @transaction.total_cost)
      elsif @transaction.sell?
        current_user.update(balance: current_user.balance + @transaction.total_cost)
      end
    end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/views/admin/transactions/index.html.erb
<div class="wrapper">
<div class="sidebar">
  <div class="logo-container">
    <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
    <span class="website-name">Stock Harbor</span>
  </div>
    <div class="menu-items">
      <%= link_to 'Add New User', new_admin_dashboard_path %>
      <%= link_to 'See All Users', '/admin/dashboard/all_users' %>
      <%= link_to 'Pending Trader Sign Ups', '/admin/dashboard/pending_sign_ups' %>
      <%= link_to 'See All Transactions', admin_transactions_index_path %>
      <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, style: 'color: white;' %>

    
    </div>
 
  </div>

<div class="transaction-content">
  <div class="transaction-wrapper">
    <h2>Transactions Log</h2>

    <div class="search-bar">
      <%= form_tag(admin_transactions_index_path, method: :get) do %>
      <%= text_field_tag :search_email, params[:search_email], placeholder: 'Search by email' %>
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
      <% end %>
    </div>

    <table>
      <thead class="transact-head">
        <tr>
          <th>User Email</th>
          <th>User ID</th>
          <th>Transaction ID</th>
          <th>Transaction Type</th>
          <th>Stock (symbol)</th>
          <th>Quantity</th>
         <!-- <th>Price during Transaction</th> -->
          <th>Total Price</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody class="transact-body">
        <% @transactions.reverse.each do |transaction| %>
          <tr class="<%= transaction.buy? ? 'buy-row' : 'sell-row' %>">
            <td><%= transaction.user.email %></td>
            <td><%= transaction.user.id %></td>
            <td><%= transaction.id %></td>
            <td><%= transaction.transaction_type %></td>
            <td><%= transaction.stock_symbol %></td>
            <td><%= transaction.quantity %></td>
            <td><%= number_to_currency(transaction.total_cost) %></td>
            <td><%= transaction.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Back to Home', admin_dashboard_index_path, class: 'btn btn-primary' %>
  </div>
</div>