config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  devise_scope :user do
    root to: "devise/sessions#new"
  end

  namespace :admin do
    get 'transactions/index'
    resources :dashboard, only: [:index, :new, :create, :edit, :update, :show] do
      get 'pending_sign_ups', to: 'dashboard#pending_sign_ups', on: :collection
      get 'all_users', to: 'dashboard#all_users', on: :collection
     
    end
  end
  
  namespace :trader do
    get 'portfolios/index'
    resources :dashboard, only: [:index, :show, :edit, :update] do
      get 'top_up', to: 'dashboard#top_up', on: :collection
      post 'top_up', to: 'dashboard#top_up', on: :collection
    end

    resources :transactions, only: [:index, :new, :create]
    resources :portfolios, only: [:index]

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all

    if params[:search_email].present?
      @transactions = @transactions.joins(:user).where('users.email LIKE ?', "%#{params[:search_email]}%")
    end
    
  end
end

app/controllers/trader/dashboard_controller.rb
class Trader::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    if params[:search].present?
      begin
        @stock = IEX::Api::Client.new.quote(params[:search])
      rescue IEX::Errors::SymbolNotFoundError
        @stock = nil
      end
        
        @market_news = fetch_market_news
        Rails.logger.debug("Market News: #{@market_news.inspect}")
    end

    begin
      @stocks = IEX::Api::Client.new.stock_market_list(:mostactive)
    rescue IEX::Errors::SymbolNotFoundError
      @stocks = []
    end

    @transactions = current_user.transactions
  end

  def top_up
    @top_up_amount = 0.0

    if request.post?
      top_up_amount = params[:top_up_amount].to_f

      if top_up_amount > 0
        current_user.top_up_balance(top_up_amount)
        flash[:notice] = "Successfully topped up your balance."
        redirect_to trader_dashboard_index_path
        return
      else
        flash.now[:alert] = "Top-up amount is invalid."
        render :top_up
      end
    end

    
  end
end


private

def set_user
  @user = User.find(params[:id])
end

def fetch_market_news
  begin
    client = IEX::Api::Client.new
    symbols = ['NFLX', 'BABA', 'FB']
    news = []

    symbols.each do |symbol|
      symbol_news = client.news(symbol).take(1)
      news.concat(symbol_news)
      Rails.logger.debug("Market News for #{symbol}: #{symbol_news.inspect}")
    end

    Rails.logger.debug("Market News: #{news.inspect}")
    news || [] 
  rescue IEX::Errors::ClientError => e
    flash[:alert] = "Error fetching market news: #{e.message}"
    Rails.logger.error("Error fetching market news: #{e.message}")
    []
  end
end

app/controllers/trader/portfolios_controller.rb
class Trader::PortfoliosController < ApplicationController
  def index
    @portfolios = []
    @total = 0

    current_user.portfolios.where.not(shares: 0).each do |portfolio|
      stock = IEX::Api::Client.new.quote(portfolio.stock)
      total = stock.latest_price * portfolio.shares
      @total += total

      @portfolios.push({
        stock: portfolio.stock,
        current_price: stock.latest_price,
        total: total,
        shares: portfolio.shares
      })
    end
  end
end

app/controllers/trader/transactions_controller.rb
class Trader::TransactionsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @user = current_user
      @transactions = @user.transactions
    end
  
    def new
      @transaction = current_user.transactions.new(transaction_params)
    end
  
    def create
      @transaction = current_user.transactions.new(transaction_params)
      if @transaction.save
          redirect_to trader_transactions_path, notice: "Transaction successful."
          update_user_balance
      else
        flash.now[:alert] = "Transaction cannot proceed."
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def transaction_params
      params.require(:transaction).permit(:stock_symbol, :quantity, :price, :transaction_type, :user_id)
    end
  
    def update_user_balance
      if @transaction.buy?
        current_user.update(balance: current_user.balance - @transaction.total_cost)
      elsif @transaction.sell?
        current_user.update(balance: current_user.balance + @transaction.total_cost)
      end
    end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/trader/dashboard_helper.rb
module Trader::DashboardHelper
end

app/helpers/trader/portfolios_helper.rb
module Trader::PortfoliosHelper
end

app/views/trader/transactions/_form.html.erb
<%= form_with(model: @transaction, url: trader_transactions_path, method: :post) do |f| %>
<div class="form-error">
  <% @transaction.errors.full_messages.each do |message| %>
    <li><%= message %></li>


  <% end %>
</div>



  <div class="transaction-form-field">
    <%= f.label :stock_symbol %><br />
    <%= f.text_field :stock_symbol, value: @transaction.stock_symbol, readonly: true %>
  </div>

  <div class="transaction-form-field">
    <%= f.label :price %><br />
    <%= f.text_field :price, value: @transaction.price, readonly: true %>
  </div>

  <div class="transaction-form-field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity, value:1, min: 1, placeholder: 'minimum: 1' %>

  </div>

  <%= f.hidden_field :user_id, value: @transaction.user.id %>
  <%= f.hidden_field :transaction_type, value: @transaction.transaction_type %>

  <% if params[:transaction][:transaction_type] == 'buy' %>

    <%= f.submit "Buy", class: 'btn btn-success' %>
  <% else %>
    <%= f.submit "Sell", class: 'btn btn-success' %>

  <% end %>
<% end %>

app/views/trader/transactions/_transaction.html.erb
<tr class="<%= transaction.buy? ? 'buy-row' : 'sell-row' %>" >
    <td><%= transaction.id %></td>
    <td><%= transaction.transaction_type %></td>
    <td><%= transaction.stock_symbol %></td>
    <td><%= transaction.quantity %></td>
    <td><%= number_to_currency(transaction.price) %></td>
    <td><%= number_to_currency(transaction.total_cost) %></td>
    <td><%= transaction.created_at.in_time_zone('Asia/Manila').strftime('%d %b %Y %H:%M') %></td>
<tr>

app/views/trader/transactions/index.html.erb
<div class='transactions_page'>
  <h1 class="transactions_page">Trader's Transaction History</h1>
  <div class= "transactions-link-container">
  <%= link_to "Back to Dashboard", trader_dashboard_index_path, class: 'btn btn-primary transactions-link' %> ||
  <%= link_to "Go To Portfolio", trader_portfolios_index_path, class: 'btn btn-primary transactions-link' %>
  
  </div>
  <div class="trans-table-container">
    <table>
   
      <thead class="trans-th">
        <tr class="trans-tr">
      
          <th>Transaction ID</th>
          <th>Transaction Type</th>
          <th>Stock (symbol)</th>
          <th>Quantity</th>
          <th>Price during Transaction</th>
          <th>Total Price</th>
          <th>Date</th>
        </tr>
      </thead>
      
      <tbody>
      
        <% @transactions.reverse.each do |transaction| %>
          <%= render(partial: 'transaction', locals: { transaction: transaction }) %>
        <% end %>
      </tbody>
    </table>
    
  </div>
  
</div>

</div>

app/views/trader/transactions/new.html.erb
<div class = 'transactions-new'>

    <h1><%= @transaction.transaction_type == 'buy' ? 'Buy' : 'Sell' %> stock</h1>
    <%= link_to "Back to dashboard", trader_dashboard_index_path, class: 'transactions-link' %>

    <div class='transaction-form-wrapper' >
        <%= render "form", method: :post, url: new_trader_transaction_path %>
    </div>

   
</div>