config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  devise_scope :user do
    root to: "devise/sessions#new"
  end

  namespace :admin do
    get 'transactions/index'
    resources :dashboard, only: [:index, :new, :create, :edit, :update, :show] do
      get 'pending_sign_ups', to: 'dashboard#pending_sign_ups', on: :collection
      get 'all_users', to: 'dashboard#all_users', on: :collection
     
    end
  end
  
  namespace :trader do
    get 'portfolios/index'
    resources :dashboard, only: [:index, :show, :edit, :update] do
      get 'top_up', to: 'dashboard#top_up', on: :collection
      post 'top_up', to: 'dashboard#top_up', on: :collection
    end

    resources :transactions, only: [:index, :new, :create]
    resources :portfolios, only: [:index]

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
    before_action :set_user, only: %i[show edit update]

    def index
        @users = User.where(role: :trader)
        @pending_traders = User.where(role: :trader, status: 'pending')
        @stock_prices = fetch_stock_prices(['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'TSLA'])
        @market_news = fetch_market_news
    end

    def pending_sign_ups
        @pending_traders = User.where(role: :trader, status: 'pending')
    end

    def all_users
        @admins = User.where(role: :admin)
        @approved_traders = User.where(role: :trader, status: 'approved')
    end
    

    def new
        @user = User.new(role: :trader)
    end
  
    def create
        @user = User.new(trader_params)
        if @user.save
            if @user.status == 'approved'
                UserMailer.approved_email(@user).deliver_later
            end
            redirect_to admin_dashboard_index_path, notice: 'Trader was created successfully.'
        else
            render :new, status: :unprocessable_entity
        end
    end
      

    def edit
    end

    def update
        if @user.update(trader_params.except(:id, :password, :password_confirmation))
          if @user.saved_change_to_status?
            if @user.status == 'approved'
              UserMailer.approved_email(@user).deliver_later
            end
          end
          redirect_to admin_dashboard_path(@user), notice: 'Trader info updated successfully.'
        else
          render :edit
        end
    end

    def show
    end

 
      

    private

    def set_user
        @user = User.find(params[:id])
    end

    def trader_params
        params.require(:user).permit(:status, :first_name, :last_name, :email, :password, :password_confirmation, :role)
    end

    def fetch_stock_prices(symbols)
        begin
          client = IEX::Api::Client.new
          stock_prices = symbols.map { |symbol| client.quote(symbol) }
          stock_prices
        rescue IEX::Errors::ClientError => e
          flash[:alert] = "Error fetching stock prices: #{e.message}"
          Rails.logger.error("Error fetching stock prices: #{e.message}")
          []
        end
      end

      def fetch_market_news
        begin
          client = IEX::Api::Client.new
          symbols = ['TSLA', 'GOOGL', 'AMZN']
          news = []
      
          symbols.each do |symbol|
            symbol_news = client.news(symbol).take(1)
            news.concat(symbol_news)
          end
      
          Rails.logger.debug("Market News: #{news.inspect}")
          news || [] 
        rescue IEX::Errors::ClientError => e
          flash[:alert] = "Error fetching market news: #{e.message}"
          Rails.logger.error("Error fetching market news: #{e.message}")
          []
        end
      end
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
end

app/controllers/trader/dashboard_controller.rb
class Trader::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    if params[:search].present?
      begin
        @stock = IEX::Api::Client.new.quote(params[:search])
      rescue IEX::Errors::SymbolNotFoundError
        @stock = nil
      end
        
        @market_news = fetch_market_news
        Rails.logger.debug("Market News: #{@market_news.inspect}")
    end

    begin
      @stocks = IEX::Api::Client.new.stock_market_list(:mostactive)
    rescue IEX::Errors::SymbolNotFoundError
      @stocks = []
    end

    @transactions = current_user.transactions
  end

  def top_up
    @top_up_amount = 0.0

    if request.post?
      top_up_amount = params[:top_up_amount].to_f

      if top_up_amount > 0
        current_user.top_up_balance(top_up_amount)
        flash[:notice] = "Successfully topped up your balance."
        redirect_to trader_dashboard_index_path
        return
      else
        flash.now[:alert] = "Top-up amount is invalid."
        render :top_up
      end
    end

    
  end
end


private

def set_user
  @user = User.find(params[:id])
end

def fetch_market_news
  begin
    client = IEX::Api::Client.new
    symbols = ['NFLX', 'BABA', 'FB']
    news = []

    symbols.each do |symbol|
      symbol_news = client.news(symbol).take(1)
      news.concat(symbol_news)
      Rails.logger.debug("Market News for #{symbol}: #{symbol_news.inspect}")
    end

    Rails.logger.debug("Market News: #{news.inspect}")
    news || [] 
  rescue IEX::Errors::ClientError => e
    flash[:alert] = "Error fetching market news: #{e.message}"
    Rails.logger.error("Error fetching market news: #{e.message}")
    []
  end
end

app/controllers/trader/portfolios_controller.rb
class Trader::PortfoliosController < ApplicationController
  def index
    @portfolios = []
    @total = 0

    current_user.portfolios.where.not(shares: 0).each do |portfolio|
      stock = IEX::Api::Client.new.quote(portfolio.stock)
      total = stock.latest_price * portfolio.shares
      @total += total

      @portfolios.push({
        stock: portfolio.stock,
        current_price: stock.latest_price,
        total: total,
        shares: portfolio.shares
      })
    end
  end
end

app/controllers/trader/transactions_controller.rb
class Trader::TransactionsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @user = current_user
      @transactions = @user.transactions
    end
  
    def new
      @transaction = current_user.transactions.new(transaction_params)
    end
  
    def create
      @transaction = current_user.transactions.new(transaction_params)
      if @transaction.save
          redirect_to trader_transactions_path, notice: "Transaction successful."
          update_user_balance
      else
        flash.now[:alert] = "Transaction cannot proceed."
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def transaction_params
      params.require(:transaction).permit(:stock_symbol, :quantity, :price, :transaction_type, :user_id)
    end
  
    def update_user_balance
      if @transaction.buy?
        current_user.update(balance: current_user.balance - @transaction.total_cost)
      elsif @transaction.sell?
        current_user.update(balance: current_user.balance + @transaction.total_cost)
      end
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/trader/dashboard_helper.rb
module Trader::DashboardHelper
end

app/helpers/trader/portfolios_helper.rb
module Trader::PortfoliosHelper
end

app/views/trader/dashboard/_stock.html.erb
<tr>
  <td><%= stock['symbol'] %></td>
  <td><%= stock['latest_price'] %></td>
  <td><%= stock['change'] %></td>
  <td><%= stock['week_52_high'] %></td>
  <td><%= stock['week_52_low'] %></td>
  <td><%= link_to "Buy", new_trader_transaction_path(transaction: { stock_symbol: stock['symbol'], price: stock['latest_price'], transaction_type: 'buy' }) %></td>
  <td><%= link_to "Sell", new_trader_transaction_path(transaction: { stock_symbol: stock['symbol'], price: stock['latest_price'], transaction_type: 'sell' }) %></td>
</tr>

app/views/trader/dashboard/index.html.erb
<% if @user.status == 'pending' %>
<div class="trader-dashboard mt-4">

<h1>Welcome <%= @user.first_name %> <%= @user.last_name %></h1>

 
  <div class="alert alert-warning mt-3">
 
    <p>Your trader status is currently <strong class="text-uppercase font-weight-bold">PENDING</strong>.</p>
    <p>Please wait for an email confirmation to be sent to <%= @user.email %>.</p>
    <p>Thank you for your patience!</p>
  </div>

  <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger mt-3' %>
<% else %>

<div class="wrapper">
<div class="sidebar">
  <div class="logo-container">
    <%= image_tag("logo.png", alt: "logo", class: "admin-logo", style: "max-width: 90px;") %>
    <span class="website-name">Stock Harbor</span>
  </div>
  <div class="menu-items">

  <%# TEMP DESIGN for transactions
  <%= link_to 'Buy Stocks', '#', class: 'custom-link buy-stocks' %>
  <%#= link_to 'Sell Stocks', '#', class: 'custom-link sell-stocks' %>

  <%= link_to 'My Portfolio', trader_portfolios_path %>
  <%= link_to 'Transaction Page', trader_transactions_path %>


  <hr class="menu-divider">
  <%= link_to 'Account Summary', '#', class: 'custom-link dividends' %>
  <%= link_to 'Stock Alerts', '#', class: 'custom-link stock-alerts' %>
  <%= link_to 'Market Analysis', '#', class: 'custom-link market-analysis' %>
  <%= link_to 'Risk Management', '#', class: 'custom-link risk-management' %>
  <%= link_to 'Tax Information', '#', class: 'custom-link tax-information' %>
 
  
  <hr class="menu-divider">
  <%= link_to 'Mobile App', '#', class: 'custom-link mobile-app' %>
  <%= link_to 'Watchlist', '#', class: 'custom-link watchlist' %>
  <%= link_to 'Research', '#', class: 'custom-link research' %>
  <%= link_to 'Trade History', '#', class: 'custom-link dividends' %>
  <%= link_to 'Dividends', '#', class: 'custom-link dividends' %>
  <%= link_to 'Settings', '#', class: 'custom-link settings' %>
  <%= link_to 'Reports', '#', class: 'custom-link reports' %>
  <%= link_to 'User Guides', '#', class: 'custom-link user-guides' %>
  <%= link_to 'Educational Resources', '#', class: 'custom-link educational-resources' %>
  <%= link_to 'Support', '#', class: 'custom-link support' %>
  <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</div>
</div>


<!-- Main Content -->
<div class="traders-wrapper">

  <div class="traders-content">
  <h1 class="wrapper-header">Welcome, <span style="color: #21ce99;"><%= current_user.first_name.capitalize %></span>!</h1>

  <div class="top-flex-container">

  <div class="add-money-wrapper">
    <!-- Add Money Form -->
    <div class="add-money-form">
      <h2>Dashboard</h2>
      <p>Current Balance: <%= number_to_currency(current_user.balance) %></p>
      <%= link_to 'Top Up', top_up_trader_dashboard_index_path, class: 'btn btn-primary topup-button', role: 'button' %>
    </div>

 
    <div class="withdraw-button">
    <%= link_to 'Withdraw', '#', class: 'withdraw-btn btn-primary', role: 'button' %>
    
    </div>
    </div>


    <!-- Stocks Section -->
    <div class="stock-container">
      <h2>Explore Stocks</h2>
      <%= form_tag(trader_dashboard_index_path, method: :get) do %>
      <div class="search-bar">
      <%= text_field_tag(:search, params[:search], placeholder: 'Enter stock symbol...') %>
      <%= submit_tag('Search', class: 'btn btn-primary') %>
    </div>
    <% end %>

  <% if @stock %>
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Stock</th>
          <th>Latest Price</th>
          <th>Change</th>
          <th>High</th>
          <th>Low</th>
          <th>Action</th>
          <th></th>
        </tr>
      </thead>
      <%= render partial: 'stock', locals: { stock: @stock } %>
    </table>
  <% else %>
    <div class="no-record">
      <h4>No records found</h4>
    </div>
  <% end %>
</div>

    </div>
    
    <div class="bottom-flex-container">

    <!-- Market News -->
<div class="trader-news-box">
  <h1 class="trader-news-heading">Market News</h1>
  <% if @market_news.present? %>
    <% @market_news.each do |article| %>
      <div class="trader-news-article">
        <h3 class="trader-article-title"><%= article['headline'] %></h3>
        <p class="trader-article-source">Source: <%= article['source'] %></p>
      </div>
    <% end %>
  <% else %>
    <p>No market news available.</p>
  <% end %>
</div>


   

<div class="trader-graph-box">
<h1 class="box-heading">Stock Prices Graph</h1>
<div id="stockGraph"></div>
</div>

</div>




  </div>
</div>


































  <% end %>

  

  
</div>

app/views/trader/dashboard/top_up.html.erb
<div class='top-up-form-container'>
  <h1>Top Up Your Balance</h1>

  <%= form_with(url: top_up_trader_dashboard_index_path, method: :post) do |form| %>
    <div class='top-up-body'>
      <%= form.label :top_up_amount, "Amount: " %>
      <%= form.number_field :top_up_amount, min: 1, value: @top_up_amount %>
    </div>

    <div class='top-up-btn-container'>
      <%= form.submit "Top Up", class: 'btn btn-success' %> || <%= link_to 'Back to Dashboard', trader_dashboard_index_path, class: 'btn btn-primary' %>
    </div>
  <% end %>


</div>